Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -12,14 +12,14 @@ jobs:
     runs-on: ubuntu-latest
     env:
       DOCKER_IMAGE: gowthamsure/pythonapp
-      #SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
-      #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-      #KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
-     # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-     # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-    permissions:
-      id-token: write   # This is required for requesting the JWT
-      contents: read    # This is required for actions/checkout
+      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+    #permissions:
+      #id-token: write   # This is required for requesting the JWT
+      #contents: read    # This is required for actions/checkout
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -36,38 +36,37 @@ jobs:
         run: |
           docker push $DOCKER_IMAGE:${{ github.sha }}
           docker push $DOCKER_IMAGE:latest
-      #- name: Official SonarQube Scan
-       # uses: SonarSource/sonarqube-scan-action@v3.0.0
-        #with:
-         # projectBaseDir: .
-          #args: >
-           # -Dsonar.projectKey=hackathon-proj -Dsonar.host.url=${{ env.SONAR_HOST_URL
-            #}} -Dsonar.login=${{ env.SONAR_TOKEN }}
-            #-Dsonar.working.directory=./.scannerwork
-      #- name: Print SonarQube Logs
-       # run: >
-        #  ls -al .scannerwork
-         # cat .scannerwork/report-task.txt || echo "report-task.txt not found"
-      #- name: SonarQube Quality Gate check
-       # id: sonarqube-quality-gate-check
-        #uses: sonarsource/sonarqube-quality-gate-action@master
-      # Force to fail step after specific time.
-       # timeout-minutes: 5
-        #env:
-         #  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
-     # - name: Configure AWS Credentials
-      #  uses: aws-actions/configure-aws-credentials@v1
-       # with:
-        #  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-         # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          #aws-region: ap-south-1
-      - name: configure aws credentials
+      - name: Official SonarQube Scan
+        uses: SonarSource/sonarqube-scan-action@v3.0.0
+        with:
+          projectBaseDir: .
+          args: >
+            -Dsonar.projectKey=hackathon-proj -Dsonar.host.url=${{ env.SONAR_HOST_URL}} -Dsonar.login=${{ env.SONAR_TOKEN }}
+            -Dsonar.working.directory=./.scannerwork
+      - name: Print SonarQube Logs
+        run: >
+          ls -al .scannerwork
+          cat .scannerwork/report-task.txt || echo "report-task.txt not found"
+      - name: SonarQube Quality Gate check
+        id: sonarqube-quality-gate-check
+        uses: sonarsource/sonarqube-quality-gate-action@master
+       Force to fail step after specific time.
+        timeout-minutes: 5
+        env:
+           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+      - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
-          role-to-assume: arn:aws:iam::891376951153:role/github-oidc-myrole
-          role-session-name: samplerolesession
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ap-south-1
+      #- name: configure aws credentials
+        #uses: aws-actions/configure-aws-credentials@v1
+        #with:
+          #role-to-assume: arn:aws:iam::891376951153:role/github-oidc-myrole
+          #role-session-name: samplerolesession
+          #aws-region: ap-south-1
  
       - name: Install kubectl
         uses: azure/setup-kubectl@v2.0
